# Generated by Django 3.2.8 on 2021-11-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210903_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeting',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
