# Generated by Django 3.2.8 on 2021-11-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_greeting_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo', models.CharField(max_length=255, verbose_name='IMO')),
                ('eedi', models.FloatField()),
                ('total_co2', models.FloatField()),
                ('total_time', models.FloatField()),
                ('total_fuel', models.FloatField()),
            ],
        ),
    ]
